### ISSUE TITLE
not importing content of .md files as strings

### ISSUE THREAD

**Issue by jsdev17** [jaywcjlove/parcel-plugin-markdown-string#1]
I'm pointing to the correct `.md` file but am getting this `/4bf131f7c7a6f8795cb4e1a26899a73e.md` instead of the content of the file as a string 😞

**Comment by jaywcjlove** [comment]
@jsdev17 Do not understand what you mean.

**Comment by jsdev17** [comment]
```jsx
import 'about' from './about.md'

console.log(about) // /4bf131f7c7a6f8795cb4e1a26899a73e.md
```

**Comment by jaywcjlove** [comment]
@jsdev17 You try a new example and try it.

**Comment by jsdev17** [comment]
try with a different file you mean?

**Comment by jaywcjlove** [comment]
@jsdev17 new example, 
https://github.com/jaywcjlove/parcel-plugin-markdown-string/tree/master/example

**Comment by jsdev17** [comment]
@jaywcjlove I'm not sure if you changed something in the code of the package or what, but I tried it again as you suggested and it's working now... Thank you!
